name: Build and Release OnePlus EmberHeart Kernel and Kernel Modules

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison flex \
            libssl-dev \
            libelf-dev \
            libdw-dev \
            build-essential \
            lz4 \
            git \
            python3 \
            curl \
            dwarves \
            cpio \
            gcc-aarch64-linux-gnu

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b lineage-23.2 \
            https://github.com/LineageOS/android_kernel_oneplus_sm8550 sm8550

          git clone --depth=1 -b lineage-23.2 \
            https://github.com/LineageOS/android_kernel_oneplus_sm8550-modules.git sm8550-modules

      - name: Download Clang (clang-r547379)
        run: |
          curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r547379.tar.gz
          mkdir -p toolchains/clang-r547379
          tar -xf clang-r547379.tar.gz -C toolchains/clang-r547379

      - name: Make Kernel Configs
        run: |
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r547379/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1

          cd sm8550
          touch .scmversion
          make O=out \
            gki_defconfig \
            vendor/kalama_GKI.config \
            vendor/oplus/kalama_GKI.config \
            vendor/debugfs.config

      - name: Build Kernel
        run: |
          export PATH="${GITHUB_WORKSPACE}/toolchains/clang-r547379/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1

          cd sm8550
          set -o pipefail
          make -j$(nproc) O=out Image 2>&1 | tee ${GITHUB_WORKSPACE}/build.log

      - name: Package AnyKernel3 zip
        run: |
          ZIP_NAME="sm8550_yaap_$(date -u +"%Y%m%d_%H%M")"

          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AnyKernel3
          cp sm8550/out/arch/arm64/boot/Image AnyKernel3/Image

          cd AnyKernel3
          zip -r9 ../"${ZIP_NAME}.zip" * -x '*.git*'

      - name: Upload Release
        run: |
          ZIP_FILE=$(ls *.zip)
          REL_NAME="${ZIP_FILE%.zip}"
          gh release create "$REL_NAME" \
            --title "$REL_NAME" \
            --notes "SM8550 YAAP kernel build" \
            "${ZIP_FILE}" \
            sm8550/out/arch/arm64/boot/Image \
            build.log
